CRITICAL - 2024-12-28 01:21:06 --> ErrorException: Declaration of CodeIgniter\I18n\TimeTrait::createFromTimestamp(int $timestamp, $timezone = null, ?string $locale = null) must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): CodeIgniter\Autoloader\Autoloader
[Method: CLI, Route: migrate]
in SYSTEMPATH\I18n\TimeTrait.php on line 268.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-12-28 01:23:02 --> ErrorException: Declaration of CodeIgniter\I18n\TimeTrait::createFromTimestamp(int $timestamp, $timezone = null, ?string $locale = null) must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): CodeIgniter\Autoloader\Autoloader
[Method: CLI, Route: migrate/rollback]
in SYSTEMPATH\I18n\TimeTrait.php on line 268.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-12-28 01:23:11 --> mysqli_sql_exception: Table 'user' already exists in C:\xampp\htdocs\PAMS\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\PAMS\system\Database\MySQLi\Connection.php(312): mysqli->query()
#1 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute()
#2 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 C:\xampp\htdocs\PAMS\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\PAMS\app\Database\Migrations\2024-12-28-011029_User.php(41): CodeIgniter\Database\Forge->createTable()
#5 C:\xampp\htdocs\PAMS\system\Database\MigrationRunner.php(867): App\Database\Migrations\User->up()
#6 C:\xampp\htdocs\PAMS\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate()
#7 C:\xampp\htdocs\PAMS\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\PAMS\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run()
#9 C:\xampp\htdocs\PAMS\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run()
#10 C:\xampp\htdocs\PAMS\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\PAMS\system\Boot.php(104): CodeIgniter\Boot::runCommand()
#12 C:\xampp\htdocs\PAMS\spark(84): CodeIgniter\Boot::bootSpark()
#13 {main}
CRITICAL - 2024-12-28 01:23:42 --> ErrorException: Declaration of CodeIgniter\I18n\TimeTrait::createFromTimestamp(int $timestamp, $timezone = null, ?string $locale = null) must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): CodeIgniter\Autoloader\Autoloader
[Method: CLI, Route: migrate]
in SYSTEMPATH\I18n\TimeTrait.php on line 268.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-12-28 01:25:04 --> ErrorException: Declaration of CodeIgniter\I18n\TimeTrait::createFromTimestamp(int $timestamp, $timezone = null, ?string $locale = null) must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): CodeIgniter\Autoloader\Autoloader
[Method: CLI, Route: migrate]
in SYSTEMPATH\I18n\TimeTrait.php on line 268.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-12-28 01:28:09 --> ErrorException: Declaration of CodeIgniter\I18n\TimeTrait::createFromTimestamp(int $timestamp, $timezone = null, ?string $locale = null) must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): CodeIgniter\Autoloader\Autoloader
[Method: CLI, Route: migrate]
in SYSTEMPATH\I18n\TimeTrait.php on line 268.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-12-28 02:06:03 --> Error: Call to undefined function form_open()
[Method: GET, Route: register]
in APPPATH\Views\v_register.php on line 32.
 1 SYSTEMPATH\View\View.php(234): include()
 2 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('v_register', [], true)
 4 APPPATH\Controllers\AuthController.php(18): view('v_register', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->register()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-28 02:06:54 --> Error: Call to undefined function form_open()
[Method: GET, Route: register]
in APPPATH\Views\v_register.php on line 32.
 1 SYSTEMPATH\View\View.php(234): include()
 2 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('v_register', [], true)
 4 APPPATH\Controllers\AuthController.php(18): view('v_register', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->register()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-28 02:06:57 --> Error: Call to undefined function form_open()
[Method: GET, Route: register]
in APPPATH\Views\v_register.php on line 32.
 1 SYSTEMPATH\View\View.php(234): include()
 2 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('v_register', [], true)
 4 APPPATH\Controllers\AuthController.php(18): view('v_register', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->register()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-12-28 02:20:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-12-28 02:21:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-12-28 02:30:14 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\PAMS\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\PAMS\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\PAMS\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\PAMS\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\PAMS\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\PAMS\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\PAMS\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\PAMS\app\Controllers\AuthController.php(40): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\PAMS\system\CodeIgniter.php(933): App\Controllers\AuthController->save_register()
#10 C:\xampp\htdocs\PAMS\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\xampp\htdocs\PAMS\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PAMS\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PAMS\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\PAMS\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-12-28 02:30:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: save_register]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `no_hp`, `password`, `role`, `created_at`, `updated_at`) VALUES (:username:, :email:, :no_hp:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(40): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->save_register()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-28 02:30:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`username`, `email`, `no_hp`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Hafa Isgianto\', \'isgiantohafa@gmail.com\', \'085540163840\', \'$2y$10$Kkzxo0lYxgA8PJ3KAwTQsOLIjPx2sHpXVAAPscsTp7JlIVESOjegO\', \'owner\', \'2024-12-28 02:30:13\', \'2024-12-28 02:30:13\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`username`, `email`, `no_hp`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Hafa Isgianto\', \'isgiantohafa@gmail.com\', \'085540163840\', \'$2y$10$Kkzxo0lYxgA8PJ3KAwTQsOLIjPx2sHpXVAAPscsTp7JlIVESOjegO\', \'owner\', \'2024-12-28 02:30:13\', \'2024-12-28 02:30:13\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `no_hp`, `password`, `role`, `created_at`, `updated_at`) VALUES (:username:, :email:, :no_hp:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(40): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->save_register()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-28 02:30:14 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `user` (`username`, `email`, `no_hp`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Hafa Isgianto\', \'isgiantohafa@gmail.com\', \'085540163840\', \'$2y$10$Kkzxo0lYxgA8PJ3KAwTQsOLIjPx2sHpXVAAPscsTp7JlIVESOjegO\', \'owner\', \'2024-12-28 02:30:13\', \'2024-12-28 02:30:13\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`username`, `email`, `no_hp`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Hafa Isgianto\', \'isgiantohafa@gmail.com\', \'085540163840\', \'$2y$10$Kkzxo0lYxgA8PJ3KAwTQsOLIjPx2sHpXVAAPscsTp7JlIVESOjegO\', \'owner\', \'2024-12-28 02:30:13\', \'2024-12-28 02:30:13\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`username`, `email`, `no_hp`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'Hafa Isgianto\', \'isgiantohafa@gmail.com\', \'085540163840\', \'$2y$10$Kkzxo0lYxgA8PJ3KAwTQsOLIjPx2sHpXVAAPscsTp7JlIVESOjegO\', \'owner\', \'2024-12-28 02:30:13\', \'2024-12-28 02:30:13\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`username`, `email`, `no_hp`, `password`, `role`, `created_at`, `updated_at`) VALUES (:username:, :email:, :no_hp:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(40): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->save_register()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-28 02:33:46 --> ErrorException: Declaration of CodeIgniter\I18n\TimeTrait::createFromTimestamp(int $timestamp, $timezone = null, ?string $locale = null) must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): CodeIgniter\Autoloader\Autoloader
[Method: CLI, Route: migrate]
in SYSTEMPATH\I18n\TimeTrait.php on line 268.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2024-12-28 02:34:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-12-28 02:39:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-12-28 02:39:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-12-28 02:39:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-12-28 03:27:46 --> mysqli_sql_exception: Table 'db_pams.users' doesn't exist in C:\xampp\htdocs\PAMS\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\PAMS\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\PAMS\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\PAMS\system\Validation\StrictRules\Rules.php(232): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\PAMS\system\Validation\Validation.php(339): CodeIgniter\Validation\StrictRules\Rules->is_unique('SCS', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\PAMS\system\Validation\Validation.php(204): CodeIgniter\Validation\Validation->processRules('username', 'Nama User', 'SCS', Array, Array, 'username')
#7 C:\xampp\htdocs\PAMS\system\Controller.php(137): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\PAMS\app\Controllers\AuthController.php(29): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\PAMS\system\CodeIgniter.php(933): App\Controllers\AuthController->save_register()
#10 C:\xampp\htdocs\PAMS\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\xampp\htdocs\PAMS\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PAMS\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PAMS\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\PAMS\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-12-28 03:27:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'db_pams.users' doesn't exist
[Method: POST, Route: AuthController/save_register]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Validation\StrictRules\Rules.php(232): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\Validation\Validation.php(339): CodeIgniter\Validation\StrictRules\Rules->is_unique('SCS', 'username', [...], null, 'username')
 4 SYSTEMPATH\Validation\Validation.php(204): CodeIgniter\Validation\Validation->processRules('username', 'Nama User', 'SCS', [...], [...], 'username')
 5 SYSTEMPATH\Controller.php(137): CodeIgniter\Validation\Validation->run()
 6 APPPATH\Controllers\AuthController.php(29): CodeIgniter\Controller->validate([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->save_register()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-28 03:27:46 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'db_pams.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'SCS\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'SCS\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Validation\StrictRules\Rules.php(232): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\Validation\Validation.php(339): CodeIgniter\Validation\StrictRules\Rules->is_unique('SCS', 'username', [...], null, 'username')
 6 SYSTEMPATH\Validation\Validation.php(204): CodeIgniter\Validation\Validation->processRules('username', 'Nama User', 'SCS', [...], [...], 'username')
 7 SYSTEMPATH\Controller.php(137): CodeIgniter\Validation\Validation->run()
 8 APPPATH\Controllers\AuthController.php(29): CodeIgniter\Controller->validate([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->save_register()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-28 03:27:46 --> [Caused by] mysqli_sql_exception: Table 'db_pams.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT 1
FROM `users`
WHERE `username` = \'SCS\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `username` = \'SCS\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `username` = \'SCS\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(232): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\Validation.php(339): CodeIgniter\Validation\StrictRules\Rules->is_unique('SCS', 'username', [...], null, 'username')
 7 SYSTEMPATH\Validation\Validation.php(204): CodeIgniter\Validation\Validation->processRules('username', 'Nama User', 'SCS', [...], [...], 'username')
 8 SYSTEMPATH\Controller.php(137): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\AuthController.php(29): CodeIgniter\Controller->validate([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->save_register()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-12-28 06:57:35 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'db_pams' in C:\xampp\htdocs\PAMS\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\PAMS\system\Database\MySQLi\Connection.php(186): mysqli->real_connect()
#1 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(1485): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(1505): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\PAMS\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists()
#6 C:\xampp\htdocs\PAMS\system\Database\MigrationRunner.php(163): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\PAMS\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\PAMS\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run()
#9 C:\xampp\htdocs\PAMS\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run()
#10 C:\xampp\htdocs\PAMS\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\PAMS\system\Boot.php(104): CodeIgniter\Boot::runCommand()
#12 C:\xampp\htdocs\PAMS\spark(84): CodeIgniter\Boot::bootSpark()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'db_pams' in C:\xampp\htdocs\PAMS\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(1485): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\PAMS\system\Database\BaseConnection.php(1505): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\PAMS\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists()
#5 C:\xampp\htdocs\PAMS\system\Database\MigrationRunner.php(163): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\PAMS\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest()
#7 C:\xampp\htdocs\PAMS\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run()
#8 C:\xampp\htdocs\PAMS\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run()
#9 C:\xampp\htdocs\PAMS\system\Boot.php(351): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\PAMS\system\Boot.php(104): CodeIgniter\Boot::runCommand()
#11 C:\xampp\htdocs\PAMS\spark(84): CodeIgniter\Boot::bootSpark()
#12 {main}
CRITICAL - 2024-12-28 06:58:17 --> ErrorException: Declaration of CodeIgniter\I18n\TimeTrait::createFromTimestamp(int $timestamp, $timezone = null, ?string $locale = null) must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): CodeIgniter\Autoloader\Autoloader
[Method: CLI, Route: migrate]
in SYSTEMPATH\I18n\TimeTrait.php on line 268.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
